# 20200121 by Al Pt (telegram@NaAlOH4)
# this file is used for let rooted shell also working


# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# If not running as shell(adb, uid 2000), don't do anything

if [ `id -u` == 0 ] && [ $0 == bash ] || [ `id -u` == 2000 ]
then
	# or we can run a bash...
	exec /system/bin/bash --rcfile /data/adb_home/.bashrc
fi


